# -*- coding: utf-8 -*-
"""Part C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYs5Uw2o2nAr3GN23uLBiAmDnFLKFz8J

### Q1: Conceptual - High Dimensionality (p > n)
**Scenario:** 100 features, 50 samples.

*   **Best Performers:**
    *   **SVM (Linear):** Designed specifically to find a separating hyperplane in high-dimensional spaces. With few samples, linear boundaries are less prone to overfitting.
    *   **Logistic Regression (with L1/L2):** Strong regularization helps prevent overfitting the noise of the 100 features.
    *   **Naive Bayes:** By assuming feature independence, it reduces the complexity of the parameter estimation, making it surprisingly robust for small sample sizes.
*   **Failures:**
    *   **Random Forest / Decision Trees:** These will likely overfit immediately by creating deep branches to isolate the small number of specific samples.
    *   **KNN:** In a 100-dimensional space with only 50 points, the 'distance' between any two points tends to converge, making the concept of 'nearest' neighbors lose its predictive power.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import StandardScaler
from scipy.stats import ttest_rel

def model_selection_report(X, y, models_dict):

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    report_data = []
    scores_cache = {}


    for name, model in models_dict.items():
        scores = cross_val_score(model, X_train_scaled, y_train, cv=kf)
        scores_cache[name] = scores
        report_data.append({'Model': name, 'Mean CV': scores.mean(), 'Std Dev': scores.std()})

    df_results = pd.DataFrame(report_data).sort_values('Mean CV', ascending=False)


    top = df_results.iloc[0]['Model']
    second = df_results.iloc[1]['Model']
    _, p_val = ttest_rel(scores_cache[top], scores_cache[second])

    print(f"Best Model: {top} (p-val vs {second}: {p_val:.4f})")
    return df_results

"""### Q3: Analyze - SVM Overfitting
**Problem:** Train Accuracy 1.0, Test Accuracy 0.52.
**Diagnosis:** The model is suffering from **high variance** (overfitting). It has effectively 'memorized' the training set noise rather than learning generalizable patterns.

**Proposed Fixes:**
1.  **Reduce C:** A high $C$ value forces the model to classify every training point correctly. Decreasing $C$ (e.g., from 100 to 0.1) creates a wider margin and allows for soft-margin misclassifications, improving generalization.
2.  **Tune Gamma:** The RBF kernel's `gamma` parameter defines how far the influence of a single training example reaches. Decrease `gamma` to make the decision boundary smoother and less reactive to individual points.
3.  **Cross-Validation & Feature Selection:** Use `GridSearchCV` to find the optimal hyperparameter balance and consider reducing the feature set if noise is causing the divergence between train and test performance.
"""