# -*- coding: utf-8 -*-
"""Part D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYs5Uw2o2nAr3GN23uLBiAmDnFLKFz8J

**Decision Tree for Algorithm Selection:**

1.  **Is the relationship between features and target likely linear?**
    *   **Yes:** Use **Logistic Regression** (fast, interpretable).
    *   **No/Unsure:** Go to 2.
2.  **Is your dataset high-dimensional (many features) but small in samples?**
    *   **Yes:** Use **SVM (Linear)** or **Naive Bayes** (avoids overfitting).
    *   **No:** Go to 3.
3.  **Are you working with non-linear boundaries and have a medium-sized dataset?**
    *   **Yes:** Use **KNN** (if scaled) or **SVM (RBF)**.
    *   **No (Large/Complex Tabular Data):** Go to 4.
4.  **Do you need high accuracy and robustness to outliers/noise?**
    *   **Yes:** Use **Random Forest** (bagging) or **GBM/XGBoost** (boosting).
    *   **If you need a quick baseline on text data:** Use **Multinomial Naive Bayes** or **LinearSVC**.

**Decision Tree for Algorithm Selection:**

1.  **Is the relationship between features and target likely linear?**
    *   **Yes:** Use **Logistic Regression** (fast, interpretable).
    *   **No/Unsure:** Go to 2.
2.  **Is your dataset high-dimensional (many features) but small in samples?**
    *   **Yes:** Use **SVM (Linear)** or **Naive Bayes** (avoids overfitting).
    *   **No:** Go to 3.
3.  **Are you working with non-linear boundaries and have a medium-sized dataset?**
    *   **Yes:** Use **KNN** (if scaled) or **SVM (RBF)**.
    *   **No (Large/Complex Tabular Data):** Go to 4.
4.  **Do you need high accuracy and robustness to outliers/noise?**
    *   **Yes:** Use **Random Forest** (bagging) or **GBM/XGBoost** (boosting).
    *   **If you need a quick baseline on text data:** Use **Multinomial Naive Bayes** or **LinearSVC**.

### Verification & Edge Cases

**Verification against experience:**
- **LR:** Matches; the best starting point for any classification task.
- **SVM/KNN:** Correctly identifies that scaling is a prerequisite (a common pitfall).
- **RF/GBM:** Correctly identifies them as the 'gold standard' for raw predictive power on tabular data.

**Edge Cases the AI might miss:**
1.  **Class Imbalance:** In cases where 99% of labels are 'Class A', most algorithms will fail. One would need to adjust `class_weight='balanced'` in SVM/RF or use resampling.
2.  **Concept Drift:** The selection guide assumes the data distribution is static. For real-time data, models like KNN are hard to update, whereas LR coefficients can be updated incrementally.
3.  **Categorical Variables with High Cardinality:** Tree-based models (RF/GBM) handle these better than distance-based models (KNN/SVM), which struggle without complex encoding.
"""