# -*- coding: utf-8 -*-
"""Part A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYs5Uw2o2nAr3GN23uLBiAmDnFLKFz8J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB

X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = [
    ('LR', LogisticRegression()),
    ('KNN', KNeighborsClassifier()),
    ('SVM', SVC()),
    ('DT', DecisionTreeClassifier()),
    ('RF', RandomForestClassifier()),
    ('GBM', GradientBoostingClassifier()),
    ('Ada', AdaBoostClassifier()),
    ('NB', GaussianNB())
]


results = []
names = []
print("Cross-Validation Accuracy:")
for name, model in models:
    cv_results = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    print(f"{name}: {cv_results.mean():.4f} ({cv_results.std():.4f})")


fig = plt.figure(figsize=(12, 6))
plt.title('Algorithm Comparison (Accuracy)')
plt.boxplot(results, labels=names, patch_artist=True)
plt.ylabel('Accuracy')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

